#!/usr/bin/env bash
# SYNTRIASS Overlay installer. Installs binaries, config templates, the systemd
# unit, and the validator onto a fresh Linux host. Idempotent; never overwrites
# an existing identity.toml. Honors DESTDIR/PREFIX/SYSCONFDIR for packaging+tests.
#
#   install.sh [--from <dir>] [--provision-self] [--no-systemd]
#     --from <dir>      directory holding the built binaries (default: ./target/release)
#     --provision-self  generate THIS node's seeds + derive/print its public keys
#     --no-systemd      install the unit file but do not enable/start it
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/lib.sh"

FROM="$HERE/../target/release"
PROVISION=0
NO_SYSTEMD=0
while [ $# -gt 0 ]; do
  case "$1" in
    --from) FROM="$2"; shift 2;;
    --provision-self) PROVISION=1; shift;;
    --no-systemd) NO_SYSTEMD=1; shift;;
    -h|--help) sed -n '2,12p' "$0"; exit 0;;
    *) die "unknown arg: $1";;
  esac
done

[ "$(id -u)" -eq 0 ] || die "install must run as root (writes ${PREFIX}, ${SYSCONFDIR})"
for b in daemon syntriass-identity webhook; do
  [ -f "$FROM/$b" ] || die "missing binary '$FROM/$b' — run: cargo build --release"
done

log "installing from $FROM (PREFIX=$PREFIX SYSCONFDIR=$SYSCONFDIR DESTDIR=${DESTDIR:-/})"

# --- service user ---
if [ -z "$DESTDIR" ] && ! id "$SVC_USER" >/dev/null 2>&1; then
  log "creating system user '$SVC_USER'"
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SVC_USER" || warn "could not create user (continuing)"
fi

# --- binaries ---
install -d -m 0755 "$(d "$PREFIX/bin")"
install -m 0755 "$FROM/daemon"            "$(d "$PREFIX/bin/$BIN_DAEMON")"
install -m 0755 "$FROM/syntriass-identity" "$(d "$PREFIX/bin/$BIN_IDENTITY")"
install -m 0755 "$FROM/webhook"           "$(d "$PREFIX/bin/$BIN_WEBHOOK")"
install -m 0755 "$HERE/validate-config.sh" "$(d "$PREFIX/bin/$VALIDATE_BIN")"
install -m 0755 "$HERE/lib.sh"            "$(d "$PREFIX/bin/syntriass-overlay-lib.sh")"
log "installed binaries: $BIN_DAEMON, $BIN_IDENTITY, $BIN_WEBHOOK, $VALIDATE_BIN"

# --- config templates (never clobber a real config) ---
install -d -m 0750 "$(d "$SYSCONFDIR")"
for f in policy identity; do
  tgt="$(d "$SYSCONFDIR/$f.toml")"
  if [ -e "$tgt" ]; then
    log "keeping existing $SYSCONFDIR/$f.toml"
  else
    install -m 0640 "$HERE/config/$f.toml.template" "$tgt"
    log "installed $SYSCONFDIR/$f.toml (from template)"
  fi
done
chmod 0600 "$(d "$SYSCONFDIR/identity.toml")" 2>/dev/null || true

# --- state dir ---
install -d -m 0750 "$(d "$STATEDIR")" "$(d "$BACKUPDIR")"

# --- docs ---
install -d -m 0755 "$(d "$DOCDIR")"
[ -f "$HERE/../docs/DEPLOYMENT_GUIDE.md" ] && install -m 0644 "$HERE/../docs/DEPLOYMENT_GUIDE.md" "$(d "$DOCDIR/DEPLOYMENT_GUIDE.md")" || true

# --- systemd unit ---
install -d -m 0755 "$(d "$UNITDIR")"
install -m 0644 "$HERE/systemd/$SERVICE" "$(d "$UNITDIR/$SERVICE")"
log "installed unit $UNITDIR/$SERVICE"

# --- optional self-provisioning ---
if [ "$PROVISION" -eq 1 ]; then
  log "provisioning THIS node's identity"
  eds="$(head -c32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  mls="$(head -c32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  pub="$("$(d "$PREFIX/bin/$BIN_IDENTITY")" "$eds" "$mls")"
  ed_pub="$(printf '%s\n' "$pub" | sed -n 's/^ed25519_public=//p')"
  ml_pub="$(printf '%s\n' "$pub" | sed -n 's/^mldsa65_public=//p')"
  ident="$(d "$SYSCONFDIR/identity.toml")"
  {
    echo "# generated by syntriass-overlay-install --provision-self"
    echo "ed25519_seed = \"$eds\""
    echo "mldsa65_seed = \"$mls\""
    echo "peer_ed25519_public = \"\"   # <- fill with the PEER's public key (below, shared OOB)"
    echo "peer_mldsa65_public = \"\""
  } > "$ident"
  chmod 0600 "$ident"
  log "wrote own seeds to $SYSCONFDIR/identity.toml (mode 600)"
  echo "================ SHARE THESE PUBLIC KEYS WITH YOUR PEER (out-of-band) ================"
  echo "this_node_ed25519_public=$ed_pub"
  echo "this_node_mldsa65_public=$ml_pub"
  echo "====================================================================================="
  log "then set peer_ed25519_public / peer_mldsa65_public from the peer's values and re-validate"
fi

# --- validate (best-effort; will FAIL until identity is provisioned) ---
if [ -z "$DESTDIR" ]; then
  log "running configuration validation"
  if "$(d "$PREFIX/bin/$VALIDATE_BIN")"; then
    log "config valid"
  else
    warn "config not yet valid — provision identity, then: $VALIDATE_BIN"
  fi
  if [ "$NO_SYSTEMD" -eq 0 ] && have_systemd; then
    systemctl daemon-reload
    log "unit installed; enable with: systemctl enable --now $SERVICE"
  else
    log "systemd not active or --no-systemd; start manually: SYNTRIASS_OVERSOCKET_LISTEN=... $BIN_DAEMON"
  fi
fi

log "install complete"
